dist: trusty
language: python
cache:
    - pip
    - apt

python:
    - 2.7
    - 3.4
    - 3.5


script:
  - python setup.py install sdist bdist bdist_wheel
  - python setup.py test


notifications:
    email:
        on_success: never
        on_failure: never
